apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragavera-web-app
  labels:
    app: ragavera-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragavera-web-app
  template:
    metadata:
      labels:
        app: ragavera-web-app
    spec:
      containers:
      - name: ragavera-web-app
        image: au.icr.io/ragavera/ragavera-web-app:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true

